version: "3.8"
services:

  graph-server:
    build:
      context: ./graph-server
    ports:
      - "8080:4001"
    networks:
      - backend
  user-service:
    build:
      context: ./user-service
    volumes:
      - ./user-service:/src/
      - nodemodules:/src/node_modules
    command: npm run start:dev
    links:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/user-db
      NODE_ENV: development
    ports:
      - "4000:4000"
      - "9231:9229"
    networks:
      - backend
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db
    ports:
      - "35000:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:1234:80
    environment:
      PGADMIN_DEFAULT_EMAIL: emreatessoy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: emre0209
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
networks:
  backend:
volumes:
  nodemodules: { }